backend:
  name: git-gateway
  branch: master

media_folder: '/assets/images/uploads'

collections:
  - name: 'pages'
    label: 'Pagine'
    delete: false
    editor:
      preview: true
    files:
      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - { label: Intro, name: intro, widget: string }
          - label: 'Works'
            name: 'works'
            widget: 'list'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Link, name: link, widget: string }
